---
- name: install kvm packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  loop: "{{ packages[ansible_distribution_release] }}"

- name: add user to libvirt group
  user:
    name: "{{ kvm_user }}"
    groups:
      - libvirt
      - kvm
    append: true
